name: First test workflow
# This is my first workflow on github
on:
  push:
  workflow_dispatch:
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
